# Generated by Django 3.2.4 on 2021-06-10 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='128 characters or fewer.Letters, numbers, hyphens and underscores.', max_length=128)),
                ('product', models.CharField(help_text='128 character or fewer', max_length=128, verbose_name='a product title')),
                ('price', models.DecimalField(decimal_places=2, help_text='a positive number or zero', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='a single product price')),
                ('quantity', models.IntegerField(default=1, help_text='a positive integer', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(verbose_name='product details')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.productbrand', verbose_name='product brand')),
            ],
        ),
    ]
